# Generated by Django 5.1.6 on 2025-04-14 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='batch_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_sys.productbatch'),
        ),
    ]
