# Generated by Django 5.1.6 on 2025-03-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer_date',
            new_name='manufacture_date',
        ),
    ]
