# Generated by Django 5.1.6 on 2025-03-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('Add stock', 'Addition'), ('Subtract stock', 'Subtraction')], max_length=20),
        ),
    ]
