# Generated by Django 5.1.6 on 2025-04-22 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0002_order_batch_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='stock_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
