# Generated by Django 5.1.6 on 2025-03-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0002_alter_stockadjustment_adjustment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('add', 'Addition'), ('subtract', 'Subtraction')], max_length=20),
        ),
    ]
