# Generated by Django 5.1.6 on 2025-02-26 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0002_order_discount_order_final_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
