# Generated by Django 5.1.6 on 2025-04-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0002_stockadjustment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
    ]
