# Generated by Django 5.2 on 2025-05-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0003_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(default='pcs', max_length=10),
        ),
    ]
