# Generated by Django 5.1.6 on 2025-03-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0003_alter_product_buying_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
