# Generated by Django 5.1.6 on 2025-04-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0003_productbatch_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='current_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
