# Generated by Django 5.1.6 on 2025-03-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0003_alter_stockadjustment_adjustment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
