# Generated by Django 5.1.6 on 2025-03-06 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0003_alter_stock_stock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_stock', models.IntegerField()),
                ('added_stock', models.IntegerField(default=0)),
                ('ordered_stock', models.IntegerField(default=0)),
                ('final_stock', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_sys.product')),
            ],
        ),
    ]
