# Generated by Django 5.1.6 on 2025-03-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0004_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
