# Generated by Django 5.2 on 2025-05-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0004_alter_product_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='new_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
