# Generated by Django 5.1.6 on 2025-03-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0004_alter_product_reorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
