# Generated by Django 5.1.6 on 2025-04-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0004_productbatch_current_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbatch',
            old_name='qty',
            new_name='initial_quantity',
        ),
    ]
