# Generated by Django 5.2 on 2025-05-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sys', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_sys.productbatch'),
        ),
    ]
